maia-httpd/maia-json/src/lib.rs
Use the serde attribute
```
#[serde(skip_serializing_if = "Option::is_none")]
```
to omit from the JSON sent in a PATCH request those fields whose value is None.
=> maia-json: omit null fields in JSON PATCH requests

maia-wasm/src/ui.rs, maia-wasm/src/ui/macros.rs, maia-wasm/src/ui/patch.rs
This addresses the problems spotted in #2, by the following changes:
* Instead of causing an uncaught error in a promise when a PATCH request fails with an error 500, we log the error to the console and terminate the promise normally.
* We do not attempt to change the RX gain unless the AGC mode is "manual".
=> maia-wasm: fix uncaught PATCH errors and gain change errors

maia-httpd/Cargo.lock, maia-httpd/Cargo.toml
This eliminates a dependency on time >= 0.1, < 0.2, which has a security problem, as reported by dependabot.
(See https://github.com/maia-sdr/maia-sdr/security/dependabot/1).
=> maia-httpd: do not use chrono default features

maia-wasm/assets/index.html, maia-wasm/assets/style.css
This removes the blank space that can appear below the UI form when the viewport is wide, by letting the waterfall grow to occupy the remaining space.
A flexbox containing the waterfall canvas and the UI form is added. This flexbox is used to control the waterfall size, which has a minimum of 75vh (this has been reduced from 80vh) but can grow to fill the remainig space of the flexbox minimum height, which is 100vh.
The UI form can cause the flexbox to overflow if the screen is narrow enough that the form doesn't fit in 25vh.
---
This is how the new layout looks like on my 1920x1080 PC screen (opening the image in a new tab is recommended, since with a white background it is difficult to tell where the screenshot ends).
This is Firefox emulating a Galaxy S20+ Android 11 Chrome 87 in …
=> maia-wasm: let waterfall grow to occupy empty viewport space

maia-wasm/src/render/engine/texture.rs, maia-wasm/src/waterfall.rs
Fix clippy lints that have appeared in rust 1.68.
=> maia-wasm: fix clippy lints

CHANGELOG.md, maia-hdl/CHANGELOG.md, maia-httpd/CHANGELOG.md, maia-httpd/Cargo.toml, maia-wasm/CHANGELOG.md, maia-wasm/Cargo.toml
Bump maia-httpd to v0.1.1 because of minor changes and maia-wasm to v0.2.0 because of API-breaking changes.
=> add CHANGELOGs and bump some versions

maia-hdl/projects/pluto/system_project.tcl
This bumps the adi-hdl submodule to the commit hash used in plutosdr-fw v0.36 and v0.37. There is no tag associated with this hash, but the branch is hdl_2021_R2. The corresponding version of Vivado is 2021.2
The path of the adi_env.tcl script has changed, so the maia-hdl pluto system_project.tcl has been updated accordingly.
=> adi-hdl: update to commit used in plutosdr-fw v0.36

.github/workflows/maia-hdl.yml
Update the maia-hdl workflow to pull the image from ghcr.io.
=> ci: move maia-sdr-devel from docker hub to ghcr.io

.github/workflows/maia-httpd.yml, maia-httpd/Cross.toml, maia-httpd/README.md
This uses a custom Docker image (taken from the maia-sdr-docker repository) to build against the buildroot uclibc toolchain using cross.
=> maia-httpd: build against buildroot toolchain with cross

CHANGELOG.md, maia-hdl/CHANGELOG.md, maia-hdl/maia_hdl/maia_sdr.py, maia-hdl/pyproject.toml
Bumps maia-hdl to v0.1.1 due to the update of adi-hdl to the Vivado 2021.2 branch.
=> bump to v0.2.1

maia-wasm/src/ui.rs
If the RX AGC is not set to Manual mode, disable the RX gain input field, since it is intended as read-only.
There is no visual change in how the web browser represents the disabled field, but it is not possible to click it and enter a value.
This closes #14.
=> maia-wasm: disable RX gain input field in AGC modes

.github/workflows/plutosdr-fw-pr-comment.yml, .github/workflows/plutosdr-fw.yml
The current approach doesn't work because we can't make comments from a pull_request triggered PR. We use another workflow that triggers when the main workflow has completed.
=> ci: fix plutosdr-fw PR comment in PRs from forks

.github/workflows/plutosdr-fw-pr-comment.yml
There was a stray dependency in the job, which made the workflow malformed.
=> ci: fix plutosdr-fw-pr-comment

.github/workflows/plutosdr-fw.yml
Otherwise the release tag an text are not updated.
=> ci:plutosdr-fw: delete existing pre-release before creating a new one

maia-httpd/maia-json/src/lib.rs, maia-httpd/src/httpd/recording.rs, maia-wasm/assets/index.html, maia-wasm/assets/style.css, maia-wasm/src/ui.rs, maia-wasm/src/ui/input.rs, maia-wasm/src/ui/macros.rs, maia-wasm/src/ui/preferences.rs
This PR addresses the suggestions in #3.
Two features are added.
This adds an option to prepend the date and time to the IQ recording filename.
A prepend_timestamp boolean field in the REST API controls whether prepending mode is active. In prepending mode, when a recording is started, the current filename is examined. If the beginning of the filename is formatted as a  timestamp, this timestamp is stripped. In other case, the filename is left as is. Next, the timestamp corresponding to the recording start (the same which is used for the SigMF metadata) is formatted as %Y-%m-%d-%H-%M-%S_ and prepended to the filename.
This adds a maximum duration field to the recorder REST API, which specifies the maximum duration for the next recording in seconds. A maximum duration of 0 indicates …
=> Recording enhancements

.github/workflows/plutosdr-fw-pr-comment.yml
This adds a debug print to the workflow, since it is being skipped when it shouldn't.
=> ci: add debug to plutosdr-fw-pr-comment workflow

.github/workflows/plutosdr-fw-pr-comment.yml
Move the 'if' to the step that adds the comment. Otherwise the debug will never print if the step is skipped.
=> ci: fix debug statement in plutosdr-fw-pr-comment

.github/workflows/plutosdr-fw-pr-comment.yml
This is giving a syntax error, so we try in another way to dump the context.
=> ci: try to fix plutosdr-fw-pr-comment

.github/workflows/plutosdr-fw-pr-comment.yml
Try to get the PR number using the get-workflow-origin action.
Using the github context to get the PR number in a workflow_run triggered workflow is unreliable, as documented in https://github.com/orgs/community/discussions/25220 We use the workaround mentioned in
https://github.com/orgs/community/discussions/25220#discussioncomment-3246923
=> ci: use get-workflow-origin in pluto-sdr-fw-pr-comment

.github/workflows/plutosdr-fw-pr-comment.yml
The correct 'if:' is applied to the job globally, so we don't need this 'if:' in the step anymore.
=> ci: remove stray 'if:' in plutosdr-fw-pr-comment

.github/workflows/maia-httpd.yml, .github/workflows/maia-json.yml, .github/workflows/maia-pac.yml, .github/workflows/maia-wasm.yml, .github/workflows/plutosdr-fw.yml, .github/workflows/publish.yml
Splits the pluto-fw workflow into two jobs to avoid rebuilding the firmware if the release creation fails, and adds actions to publish the Rust crates to crates.io on tag pushes.
=> ci: some updates

.github/workflows/plutosdr-fw.yml
Now that we have tags such as maia-json-..., we need to change the way that the latests maia-sdr tag is found.
=> ci:plutosdr-fw: fix latest XSA discovery

.github/workflows/plutosdr-fw.yml
Try to delete only the pre-release tag to avoid the new pre-released being in a draft state after the action finishes.
=> ci:plutosdr-fw: do not delete previous pre-release

.github/workflows/plutosdr-fw.yml
The commit of the action-gh-release has changed, since the previous one was not built correctly.
=> ci:plutosdr-fw: fix action-gh-release commit

maia-hdl/maia_hdl/spectrum_integrator.py
A warning was being given because the counter for the spectrum integrator had a negative reset value (while it is unsigned). To fix this, we take modulo to make the reset value positive.
This fixes #27.
=> maia-hdl: fix spectrum integrator reset value

CHANGELOG.md, maia-hdl/CHANGELOG.md, maia-hdl/maia_hdl/clknx.py, maia-hdl/maia_hdl/maia_sdr.py, maia-hdl/pyproject.toml, maia-hdl/test_cocotb/cmult3x/verilog.py
This makes a change in the `ClkNxCommonEdge` module to improve timing, since release v0.4.0 was not closing timing when building the Pluto bitstream.
=> v0.5.0 release: fix timing in v0.4.0

.github/workflows/plutosdr-fw.yml
This is the first test to get building the PlutoSDR firmware with Vivado running on a self-hosted runner.
=> ci: replace plutosdr-fw runner by self-hosted

.github/workflows/plutosdr-fw.yml, README.md
This uses Vivado to build the bitstream and FSBL instead of using the bitstream in a pre-built XSA file.
=> ci: build plutosdr-fw without XSA file

.github/workflows/plutosdr-fw.yml, CHANGELOG.md, maia-hdl/test/test_cmult.py, maia-hdl/test/test_cpwr.py, maia-hdl/test/test_mult2x.py, maia-hdl/test_cocotb/dma/test_dma.py, maia-hdl/test_cocotb/dma_stream/test_dma_stream.py, maia-httpd/CHANGELOG.md, maia-httpd/Cargo.lock, maia-httpd/Cargo.toml, maia-httpd/src/sigmf.rs, maia-wasm/CHANGELOG.md, maia-wasm/Cargo.lock, maia-wasm/Cargo.toml, maia-wasm/waterfall-example/Cargo.lock, maia-wasm/waterfall-example/Cargo.toml
This introduces a commit to fix the SigMF `core:datetime` formatting in maia-httpd, updates the dependencies of all the Rust crates, and bumps a new release version.
=> Fix SigMF core:datetime formatting and release

maia-httpd/.cargo/config.toml, maia-httpd/Cargo.toml, maia-wasm/Cargo.toml, maia-wasm/waterfall-example/Cargo.toml
Use codegen-units=1 in maia-httpd and maia-wasm. Use CPU flags for the Zynq Cortex A9 in maia-httpd.
=> maia-httpd,maia-wasm: optimize code generation

maia-httpd/src/sigmf.rs
According to https://github.com/sigmf/SigMF/pull/298 the SigMF version should not have a leading `v`.
=> maia-httpd: fix sigmf version format

maia-httpd/Cargo.lock, maia-httpd/Cargo.toml, maia-httpd/src/httpd.rs, maia-httpd/src/httpd/recording.rs, maia-httpd/src/httpd/zeros.rs
This requires a few code changes due a major version change in axum.
=> maia-httpd: bump axum to v0.7

.github/workflows/plutosdr-fw.yml, maia-httpd/Cross.toml
This fixes the `plutosdr-fw.yml` workflow by updating it to Vivado 2022.2 and removes the custom `Cross.toml` for maia-httpd.
=> Some fixes for the build system

.github/workflows/maia-hdl.yml, .github/workflows/maia-httpd.yml, .github/workflows/maia-json.yml, .github/workflows/maia-wasm.yml, .github/workflows/publish.yml, .github/workflows/waterfall-example.yaml
The v3 action uses a deprecated NodeJS version.
=> ci: update checkout actions to v4

maia-httpd/Cargo.lock, maia-httpd/Cargo.toml, maia-httpd/src/fpga.rs, maia-httpd/src/httpd.rs, maia-httpd/src/httpd/version.rs, maia-wasm/Cargo.lock, maia-wasm/Cargo.toml, maia-wasm/src/lib.rs, maia-wasm/src/version.rs
This adds a page /version that lists version information about maia-httpd, maia-hdl and maia-wasm. maia-httpd has the information for itself filled in at compile time, and reads /etc/libiio.ini to get the firmware version, and the maia-hdl IP core registers to get the maia-hdl version. It generates a page with this information and some `<span>`'s that are filled in by JavaScript that calls maia-wasm functions that return the maia-wasm version information.
=> maia-httpd,maia-wasm: add version information page

maia-httpd/Cargo.lock, maia-httpd/Cargo.toml, maia-httpd/src/ddc.rs
Since pm-remez 0.1.2, the ichige function is available in pm-remez, so it has been removed from maia-httpd.
=> maia-httpd: use ichige function from pm-remez

maia-hdl/projects/pluto/system_bd.tcl, maia-hdl/projects/pluto_iio/Makefile, maia-hdl/projects/pluto_iio/system_bd.tcl, maia-hdl/projects/pluto_iio/system_project.tcl, maia-hdl/projects/plutoplus_iio/Makefile, maia-hdl/projects/plutoplus_iio/system_bd.tcl, maia-hdl/projects/plutoplus_iio/system_project.tcl
Preserve original design (specially addresses of dma) by adding maia-iio in maia_hdl
maia-sdr and standard iio in parallel
Add CS8 RX and TX (naive implementation)
=> Add maia-iio : pluto and pluto plus hdl running in parallel of iio

maia-hdl/maia_hdl/fft.py, maia-hdl/test/test_fft.py
Improve the test of the FFT model against the numpy FFT by:
- Generating inputs that cover all the set of allowed values
- Testing also the case when a truncate of 0 is used in every stage
- Reducing the relative error threshold from 3e-3 to 4e-4 (the test still passes).
Additionally, clarify the allowed set of input values to prevent internal overflows in the FFT docstring.
=> maia-hdl: improve FFT model test

.github/workflows/plutosdr-fw.yml
I have seen cases of the docker compose build failing and the pipeline calling it good, so it looks like the Upload artifacts step still needs if-no-files-found: error.
=> ci: error if there are no artifcats

maia-httpd/Cargo.lock, maia-httpd/Cargo.toml, maia-httpd/src/httpd/websocket.rs
Update dependencies to fix an openssl security advisory. This also involves an API-breaking update of axum.
=> maia-httpd: update dependencies

maia-httpd/src/httpd.rs
In c7d595ef06ea5c368be49a3f18b8669eaca2b4eb there was an API-breaking update of axum. This built successfully, but was not tested. There are some runtime errors caused by this update, due to a change in the syntax for extractors, as described in:
https://github.com/joelparkerhenderson/demo-rust-axum/blob/main/README.md#caution-extractors-syntax-change
This fixes the problem.
=> maia-httpd: fix regression caused by axum update

maia-httpd/maia-json/src/lib.rs, maia-httpd/src/httpd.rs, maia-httpd/src/httpd/api.rs, maia-httpd/src/httpd/version.rs, maia-wasm/assets/index.html, maia-wasm/src/ui.rs
This adds the versions information to the maia-httpd REST API and displays them in the "Other" in settings tab in the maia-wasm web UI.
=> Incorporate version information as part of the settings dialog

maia-httpd/Cargo.lock, maia-httpd/src/sigmf.rs, maia-wasm/Cargo.lock, maia-wasm/src/waterfall.rs
Version 1.2.3 is the latest version of the SigMF specification. maia-httpd doesn't use at the moment any new features in this version of the specification, but it still makes sense to use that instead of 1.0.0.
=> maia-httpd: bump sigmf version to 1.2.3

.github/workflows/maia-hdl.yml
Apparently build is no longer installed by default in the ubuntu-latest Github runner, so this workflow is failing.
=> ci: install build before building maia-hdl package
